name: Release
on:
  push:
    branches:
      - 'master'

  workflow_dispatch:
    inputs:
      version:
        description: VERSION
        required: true

env:
  pkgn: ibus

jobs:
  build:
    runs-on: ubuntu-20.04 # ubuntu-latest # it currently uses the Ubuntu 22.04 runner image, which uses zst compression
    # https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # with:
      #   submodules: true

    - name: Install equivs
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: equivs

    - name: Build 
      run: equivs-build $pkgn-dummy

    - name: Upload release for Debian
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: deb
        owner: suntong
        repo: repo
        distro: any-distro
        release: any-version
        # republish: "true" # needed ONLY if version is not changing
        file: $pkgn-dummy_*_all.deb
